### ISSUE TITLE
Crash on quit

### ISSUE THREAD

**Issue by Brandantl** [yourWaifu/sleepy-discord#81]
I downloaded the latest from the Develop branch and now it crashes on exit.

![image](https://user-images.githubusercontent.com/6909044/40649688-67c9f26c-62e6-11e8-81c3-e5e759f3b86c.png)
![image](https://user-images.githubusercontent.com/6909044/40649757-8d1f8c84-62e6-11e8-82ef-c8738e333388.png)
![image](https://user-images.githubusercontent.com/6909044/40649770-94cbb372-62e6-11e8-96d5-4be848dc2b60.png)

**Comment by yourWaifu** [comment]
It's hard to say what's causing the crash. What I can see is that it looks like you are using mode '''USE_RUN_THREAD'''. Which to be honest, I haven't used in like forever. The run thread is used for scheduling events and websocket connections. I'm not sure if you really need this thread but try using '''USER_CONTROLED_THREADS''', do not that this isn't documented just yet but the example have already been updated if you need examples.

**Comment by yourWaifu** [comment]
change
```
TIPBOT client(GlobalConfig.General.discordToken, 2);
```
to 
```
TIPBOT client(GlobalConfig.General.discordToken, SleepyDiscord::USER_CONTROLED_THREADS);
```
Sorry about this, I noticed that a number of users were getting confused about the number so I changed it. I must of changed to the number to better represent how many threads are actually being used.

**Comment by Brandantl** [comment]
I just reverted to the last known working version I had compiled. It's broken on the most recent sleepy discord though.

**Comment by Brandantl** [comment]
So the quit() is functioning correctly but when the class destructs afterwards it crashes in the WebsocketppDiscordClient destructor. 

We cleanly exited the sleepy discord run() function here (which is what Tbot.start(); does) 

![image](https://user-images.githubusercontent.com/6909044/42614345-5cee6314-855a-11e8-8d37-433d86f457a6.png)


I think there is an issue with the order in which the destructors are working or that _thread isn't being set to nullptr after quit() is invoked and the threads are shutdown. It reads 0xcccccccc

**Comment by Brandantl** [comment]
(*((SleepyDiscord::WebsocketppDiscordClient*)&(*((Discord*)&Tbot))))._thread 

is NEVER initialized in the life time of the application.

**Comment by yourWaifu** [comment]
actually that makes sense, most of the time, it does nothing unless you asked for more threads. I thought ``if (thread)``, I can't remember why reset is being called since that was written so long ago.

**Comment by Brandantl** [comment]
I'll make a pull request in a bit to fix it when my exact change show in the image above.

**Comment by Brandantl** [comment]
Even crashes on exit with this code
![image](https://user-images.githubusercontent.com/6909044/43983989-819fd9da-9cb2-11e8-931d-ae13e4c96963.png)

**Comment by yourWaifu** [comment]
I'm actually currently making some changes to quit that should fix this issue. I think it should be finished by tomorrow.

**Comment by Brandantl** [comment]
No problem I was trying to find it using my commercial memory checkers and couldn't locate it for some reason. I'll check with valgrind to see if i can pinpoint it.

**Comment by Brandantl** [comment]
Nope couldn't figure it out. I'll test it again once you refactor quit() and the shutdown process.
![image](https://user-images.githubusercontent.com/6909044/43984996-f7a58cc8-9cb8-11e8-915a-ae6f489412aa.png)

**Comment by Brandantl** [comment]
Stack corruption still occurs on https://github.com/yourWaifu/sleepy-discord/commit/325e770b2eb6602a8312b38bff6ba6e099b307dd
![image](https://user-images.githubusercontent.com/6909044/43987314-c703f788-9cd3-11e8-80f7-c2fcabb6f91b.png)

**Comment by yourWaifu** [comment]
I did some testing and found that adding the predecessor define ``SLEEPY_VOICE_ENABLED`` fixes this, and this is why I'm not getting this error. I'll see what ``SLEEPY_VOICE_ENABLED`` has to do with this issue.

**Comment by Brandantl** [comment]
G++ won't allow you to compile because of a local being returned from a reference function.
![image](https://user-images.githubusercontent.com/6909044/43988728-8e8b8714-9cf0-11e8-9a5b-5f74c2e77d82.png)

**Comment by yourWaifu** [comment]
you can remove that function, it's not use nor does it work.

**Comment by yourWaifu** [comment]
Ok nevermind, it is used. I'll have to fix that
